import { evaluationCategories, type Evidence, type MarketCandidate, type UserConstraints } from "./types.ts";

const createEvidence = (subject: string, confidence: number, gaps: string[] = []): Evidence => ({
  facts: [`${subject} に関する既知のダミー事実を整理済み`],
  inferences: [`${subject} は現時点でも検証優先度が高いと推定`],
  assumptions: [`${subject} の商流は今後12か月は大きく変化しない前提`],
  missingInformation: gaps,
  supportingEvidence: [`既存業務での反復作業が多く、導入余地がある想定`],
  counterEvidence: [`競合参入で単価が圧縮される可能性がある`],
  sources: ["MVPダミーデータ v1"],
  confidence,
});

const createCategoryEvidence = (
  seed: string,
  confidence: number,
  uncoveredCategories: string[] = [],
): MarketCandidate["categoryEvidence"] => {
  return Object.fromEntries(
    evaluationCategories.map((category) => [
      category,
      createEvidence(
        `${seed} / ${category}`,
        confidence,
        uncoveredCategories.includes(category) ? ["追加の一次ヒアリングが必要"] : [],
      ),
    ]),
  ) as MarketCandidate["categoryEvidence"];
};

export const defaultUserConstraints: UserConstraints = {
  freeText: "日本国内で、少人数でも始めやすく、半年以内に検証できるB2B事業を探したい。",
  budget: 8000000,
  skills: ["sales", "operations", "ai", "product"],
  timeframeMonths: 6,
  teamSize: 3,
  region: "japan",
  preferredBusinessModel: "subscription",
  targetMonthlyRevenue: 1500000,
  riskTolerance: "medium",
  excludedMarkets: ["医療診断"],
};

export const marketCandidates: MarketCandidate[] = [
  {
    id: "manufacturing-maintenance-ai",
    name: "製造業向け予防保全AI SaaS",
    summary: "設備保全の紙・Excel運用を置き換え、停止損失を減らすB2B SaaS。",
    targetCustomer: "中小〜中堅製造業の工場長・保全部門",
    regionFocus: ["japan", "asia"],
    businessModels: ["subscription"],
    tags: ["製造", "B2B", "SaaS"],
    budgetRequired: 7000000,
    teamRequired: 3,
    minimumDurationMonths: 5,
    requiredSkills: ["ai", "product", "sales"],
    regulatoryRisk: "low",
    categoryScores: {
      demand: 82,
      growth: 73,
      demandSupplyGap: 77,
      customerPain: 88,
      competition: 61,
      profitability: 76,
      acquisitionDifficulty: 58,
      feasibility: 72,
      durability: 75,
      risk: 71,
    },
    categoryEvidence: createCategoryEvidence("製造保全AI", 78, ["competition"]),
    topReasons: ["停止損失の痛みが強い", "継続課金に向く運用課題", "少人数でも検証しやすい"],
    maxRisk: "導入決裁が長く、初回受注まで営業リードタイムが伸びやすい",
  },
  {
    id: "restaurant-inventory-saas",
    name: "飲食店向け在庫最適化 SaaS",
    summary: "食材ロス削減と発注最適化を支援する多店舗向け SaaS。",
    targetCustomer: "複数店舗を持つ飲食チェーン本部",
    regionFocus: ["japan"],
    businessModels: ["subscription"],
    tags: ["飲食", "SaaS", "在庫"],
    budgetRequired: 4500000,
    teamRequired: 2,
    minimumDurationMonths: 4,
    requiredSkills: ["product", "operations", "sales"],
    regulatoryRisk: "low",
    categoryScores: {
      demand: 74,
      growth: 64,
      demandSupplyGap: 69,
      customerPain: 79,
      competition: 55,
      profitability: 71,
      acquisitionDifficulty: 63,
      feasibility: 83,
      durability: 62,
      risk: 76,
    },
    categoryEvidence: createCategoryEvidence("飲食在庫最適化", 74, ["growth", "durability"]),
    topReasons: ["低予算でPoCしやすい", "現場課題が分かりやすい", "継続利用の余地がある"],
    maxRisk: "既存POSや発注システムとの連携要望が強くなりやすい",
  },
  {
    id: "crossborder-ops-service",
    name: "越境EC運用代行プラットフォーム",
    summary: "国内ブランド向けに越境ECの出店・CS・物流調整を一体で提供する。",
    targetCustomer: "海外販売を始めたいD2Cブランド",
    regionFocus: ["japan", "global"],
    businessModels: ["project", "marketplace"],
    tags: ["越境EC", "運用代行", "D2C"],
    budgetRequired: 9000000,
    teamRequired: 4,
    minimumDurationMonths: 6,
    requiredSkills: ["operations", "sales"],
    regulatoryRisk: "medium",
    categoryScores: {
      demand: 78,
      growth: 81,
      demandSupplyGap: 70,
      customerPain: 72,
      competition: 57,
      profitability: 68,
      acquisitionDifficulty: 54,
      feasibility: 60,
      durability: 59,
      risk: 60,
    },
    categoryEvidence: createCategoryEvidence("越境EC運用代行", 69, ["profitability", "risk"]),
    topReasons: ["成長市場に乗りやすい", "最初は人力運用で立ち上げやすい", "複数収益源を作れる"],
    maxRisk: "物流・CSの運用品質が粗いと解約や赤字に直結しやすい",
  },
  {
    id: "senior-iot-monitoring",
    name: "高齢者見守り IoT サービス",
    summary: "家族・介護事業者向けに生活異常を通知する見守りサービス。",
    targetCustomer: "在宅介護世帯と地域介護事業者",
    regionFocus: ["japan", "local"],
    businessModels: ["subscription", "ecommerce"],
    tags: ["介護", "IoT", "見守り"],
    budgetRequired: 12000000,
    teamRequired: 4,
    minimumDurationMonths: 8,
    requiredSkills: ["hardware", "operations", "sales"],
    regulatoryRisk: "medium",
    categoryScores: {
      demand: 80,
      growth: 72,
      demandSupplyGap: 66,
      customerPain: 86,
      competition: 58,
      profitability: 61,
      acquisitionDifficulty: 49,
      feasibility: 44,
      durability: 73,
      risk: 55,
    },
    categoryEvidence: createCategoryEvidence("高齢者見守りIoT", 67, ["feasibility"]),
    topReasons: ["社会課題が明確", "継続利用の必然性が高い", "地域連携で差別化しやすい"],
    maxRisk: "ハードウェア運用負荷とサポートコストが重い",
  },
  {
    id: "field-sales-training-saas",
    name: "法人営業向け商談トレーニング SaaS",
    summary: "商談記録をもとに営業育成とナレッジ共有を効率化するB2B SaaS。",
    targetCustomer: "営業組織を持つSaaS・人材・IT企業",
    regionFocus: ["japan", "global"],
    businessModels: ["subscription"],
    tags: ["営業", "育成", "SaaS"],
    budgetRequired: 6500000,
    teamRequired: 3,
    minimumDurationMonths: 4,
    requiredSkills: ["sales", "product", "ai"],
    regulatoryRisk: "low",
    categoryScores: {
      demand: 76,
      growth: 77,
      demandSupplyGap: 65,
      customerPain: 68,
      competition: 48,
      profitability: 79,
      acquisitionDifficulty: 66,
      feasibility: 78,
      durability: 57,
      risk: 73,
    },
    categoryEvidence: createCategoryEvidence("営業トレーニングSaaS", 76, ["demandSupplyGap"]),
    topReasons: ["サブスク適性が高い", "既存営業ノウハウを生かしやすい", "少人数でも構築可能"],
    maxRisk: "競争環境が激しく、差別化が曖昧だと価格競争になりやすい",
  },
  {
    id: "online-medical-diagnosis",
    name: "オンライン医療診断プラットフォーム",
    summary: "症状入力から診断補助・受診導線までをまとめるヘルスケア基盤。",
    targetCustomer: "個人患者と医療機関",
    regionFocus: ["japan"],
    businessModels: ["subscription", "marketplace"],
    tags: ["医療診断", "ヘルスケア", "規制"],
    budgetRequired: 15000000,
    teamRequired: 5,
    minimumDurationMonths: 9,
    requiredSkills: ["medical", "ai", "product"],
    regulatoryRisk: "critical",
    categoryScores: {
      demand: 85,
      growth: 75,
      demandSupplyGap: 63,
      customerPain: 83,
      competition: 46,
      profitability: 74,
      acquisitionDifficulty: 37,
      feasibility: 28,
      durability: 64,
      risk: 18,
    },
    categoryEvidence: createCategoryEvidence("オンライン医療診断", 58, ["risk", "feasibility", "competition"]),
    topReasons: ["需要自体は大きい", "社会的意義が高い", "成功時の市場インパクトが大きい"],
    maxRisk: "重大な法規制・責任リスクがありMVP段階では足切り対象になりやすい",
  },
];
