import { evaluationCategories, type Evidence, type MarketCandidate, type UserConstraints } from "./types";

const createEvidence = (
  id: string,
  signalGroup: string,
  subject: string,
  confidence: number,
  gaps: string[] = [],
): Evidence => ({
  id,
  signalGroup,
  facts: [`${subject} に関する既知のダミー事実を整理済み`],
  inferences: [`${subject} は現時点でも検証優先度が高いと推定`],
  assumptions: [`${subject} の商流は今後12か月は大きく変化しない前提`],
  missingInformation: gaps,
  supportingEvidence: ["既存業務での反復作業が多く、導入余地がある想定"],
  counterEvidence: ["競合参入で単価が圧縮される可能性がある"],
  sources: ["MVPダミーデータ v1"],
  confidence,
});

const createCategoryEvidence = (
  seed: string,
  confidence: number,
  uncoveredCategories: string[] = [],
): MarketCandidate["categoryEvidence"] => Object.fromEntries(
  evaluationCategories.map((category) => {
    const isUncovered = uncoveredCategories.includes(category);
    const evidence = createEvidence(
      `${seed}-${category}`,
      `${seed}-${category}`,
      `${seed} / ${category}`,
      confidence,
      isUncovered ? ["追加の一次ヒアリングが必要"] : [],
    );
    return [category, isUncovered ? { ...evidence, facts: [], supportingEvidence: [] } : evidence];
  }),
) as MarketCandidate["categoryEvidence"];

export const defaultUserConstraints: UserConstraints = {
  freeText: "初心者でも小さく試せて、1人で始めやすいビジネスの市場を探したい。",
  budget: 100000,
  skills: ["ai"],
  unavailableSkills: [],
  timeframeMonths: 3,
  teamSize: 1,
  weeklyHours: 12,
  region: "japan",
  preferredBusinessModel: "any",
  targetMonthlyRevenue: 300000,
  riskTolerance: "medium",
  excludedMarkets: ["医療診断"],
};

export const marketCandidates: MarketCandidate[] = [
  {
    id: "manufacturing-maintenance-ai",
    name: "製造業向け予防保全AI SaaS",
    summary: "工場の点検や故障予測をAIで助ける月額サービス。最初は簡単なデモとヒアリングから検証できます。",
    targetCustomer: "中小〜中堅製造業の工場長・保全部門",
    regionFocus: ["japan", "asia"],
    businessModels: ["subscription"],
    tags: ["製造", "B2B", "SaaS", "AI"],
    budgetRequired: 200000,
    teamRequired: 1,
    weeklyHoursRequired: 12,
    minimumDurationMonths: 2,
    requiredSkills: ["ai", "sales"],
    regulatoryRisk: "low",
    categoryScores: { demand: 82, growth: 73, demandSupplyGap: 77, customerPain: 88, competition: 61, profitability: 76, acquisitionDifficulty: 58, feasibility: 72, durability: 75, risk: 71 },
    categoryEvidence: createCategoryEvidence("製造保全AI", 78, ["competition"]),
    topReasons: ["工場停止の損失が大きく困りごとが強い", "月額サービスにしやすい", "小さなデモから需要確認できる"],
    maxRisk: "企業向けなので、最初のお客さんを見つけるまで時間がかかることがある",
  },
  {
    id: "restaurant-inventory-saas",
    name: "飲食店向け在庫・発注サポート",
    summary: "食材ロスを減らし、発注を楽にするサービス。まずは表計算や簡単なWeb画面でも試せます。",
    targetCustomer: "複数店舗を持つ飲食店や小規模チェーン",
    regionFocus: ["japan"],
    businessModels: ["subscription"],
    tags: ["飲食", "SaaS", "在庫", "店舗"],
    budgetRequired: 80000,
    teamRequired: 1,
    weeklyHoursRequired: 8,
    minimumDurationMonths: 1,
    requiredSkills: ["operations", "sales"],
    regulatoryRisk: "low",
    categoryScores: { demand: 74, growth: 64, demandSupplyGap: 69, customerPain: 79, competition: 55, profitability: 71, acquisitionDifficulty: 63, feasibility: 83, durability: 62, risk: 76 },
    categoryEvidence: createCategoryEvidence("飲食在庫最適化", 74, ["growth", "durability"]),
    topReasons: ["小さく試しやすい", "困りごとが分かりやすい", "継続利用につながりやすい"],
    maxRisk: "POSや発注システムとの連携を求められると開発が難しくなる",
  },
  {
    id: "crossborder-ops-service",
    name: "海外販売の運用代行",
    summary: "国内ブランドの海外販売を、出品・問い合わせ対応・物流調整までまとめて手伝うサービス。",
    targetCustomer: "海外販売を始めたい小規模ブランド",
    regionFocus: ["japan", "global"],
    businessModels: ["project", "marketplace"],
    tags: ["越境EC", "運用代行", "D2C", "海外販売"],
    budgetRequired: 100000,
    teamRequired: 1,
    weeklyHoursRequired: 10,
    minimumDurationMonths: 2,
    requiredSkills: ["operations", "sales"],
    regulatoryRisk: "medium",
    categoryScores: { demand: 78, growth: 81, demandSupplyGap: 70, customerPain: 72, competition: 57, profitability: 68, acquisitionDifficulty: 54, feasibility: 60, durability: 59, risk: 60 },
    categoryEvidence: createCategoryEvidence("越境EC運用代行", 69, ["profitability", "risk"]),
    topReasons: ["最初は人力でも始められる", "海外販売ニーズを狙える", "受託から始めやすい"],
    maxRisk: "返品や物流トラブルの対応が増えると手間が大きくなる",
  },
  {
    id: "senior-iot-monitoring",
    name: "高齢者見守りサービス",
    summary: "家族や介護事業者に異変を知らせる見守りサービス。機器を使うため、他候補より少し難易度が高めです。",
    targetCustomer: "在宅介護世帯と地域介護事業者",
    regionFocus: ["japan", "local"],
    businessModels: ["subscription", "ecommerce"],
    tags: ["介護", "IoT", "見守り", "ハードウェア"],
    budgetRequired: 300000,
    teamRequired: 2,
    weeklyHoursRequired: 15,
    minimumDurationMonths: 3,
    requiredSkills: ["hardware", "operations"],
    regulatoryRisk: "medium",
    categoryScores: { demand: 80, growth: 72, demandSupplyGap: 66, customerPain: 86, competition: 58, profitability: 61, acquisitionDifficulty: 49, feasibility: 44, durability: 73, risk: 55 },
    categoryEvidence: createCategoryEvidence("高齢者見守りIoT", 67, ["feasibility"]),
    topReasons: ["困りごとが明確", "継続利用されやすい", "地域で差別化できる"],
    maxRisk: "機器の故障対応やサポートが必要で、1人では負担が増えやすい",
  },
  {
    id: "field-sales-training-saas",
    name: "営業練習AIツール",
    summary: "営業トークの練習や振り返りをAIで助ける月額サービス。簡単な試作品から始められます。",
    targetCustomer: "営業チームを持つ中小企業・IT企業",
    regionFocus: ["japan", "global"],
    businessModels: ["subscription"],
    tags: ["営業", "育成", "SaaS", "AI"],
    budgetRequired: 80000,
    teamRequired: 1,
    weeklyHoursRequired: 10,
    minimumDurationMonths: 2,
    requiredSkills: ["ai", "sales"],
    regulatoryRisk: "low",
    categoryScores: { demand: 76, growth: 77, demandSupplyGap: 65, customerPain: 68, competition: 48, profitability: 79, acquisitionDifficulty: 66, feasibility: 78, durability: 57, risk: 73 },
    categoryEvidence: createCategoryEvidence("営業トレーニングSaaS", 76, ["demandSupplyGap"]),
    topReasons: ["月額課金にしやすい", "AIで試作品を作りやすい", "1人でも需要確認しやすい"],
    maxRisk: "似たサービスが多く、特徴が弱いと選ばれにくい",
  },
  {
    id: "online-medical-diagnosis",
    name: "オンライン医療診断プラットフォーム",
    summary: "症状入力から診断補助・受診案内までを行う医療サービス。法律・安全面の確認が非常に重要です。",
    targetCustomer: "個人患者と医療機関",
    regionFocus: ["japan"],
    businessModels: ["subscription", "marketplace"],
    tags: ["医療診断", "ヘルスケア", "規制"],
    budgetRequired: 300000,
    teamRequired: 2,
    weeklyHoursRequired: 15,
    minimumDurationMonths: 3,
    requiredSkills: ["medical", "ai"],
    regulatoryRisk: "critical",
    categoryScores: { demand: 85, growth: 75, demandSupplyGap: 63, customerPain: 83, competition: 46, profitability: 74, acquisitionDifficulty: 37, feasibility: 28, durability: 64, risk: 18 },
    categoryEvidence: createCategoryEvidence("オンライン医療診断", 58, ["risk", "feasibility", "competition"]),
    topReasons: ["需要自体は大きい", "社会的な課題が大きい", "成功時の影響が大きい"],
    maxRisk: "法律・医療責任・安全性のハードルが高く、初心者が個人で始める候補には向きにくい",
  },
];
