import type { BusinessCandidate, BusinessProfile } from "./types";

export const defaultBusinessProfile: BusinessProfile = {
  freeText: "できれば3万円くらいから、1人で小さく始められるビジネスを探したい。AIも使いたい。",
  startingBudget: 30000,
  weeklyHours: 12,
  targetMonthlyIncome: 300000,
  timeToFirstRevenueMonths: 3,
  solo: true,
  salesComfort: 2,
  technicalComfort: 3,
  aiComfort: 4,
  inventoryOkay: false,
  faceOnCameraOkay: false,
  localServiceOkay: true,
  riskTolerance: "medium",
  interests: ["AI", "アプリ", "動画"],
  avoid: [],
};

export const businessCandidates: BusinessCandidate[] = [
  {
    id: "ai-automation-agency",
    name: "AIで会社の作業を自動化する代行",
    summary: "会社の繰り返し作業をAIで楽にして、その設定やサポート料金をもらう。",
    category: "AIサービス",
    marketOpportunityScore: 82,
    requiredBudget: 10000,
    requiredWeeklyHours: 12,
    monthsToFirstRevenue: 1,
    estimatedMonthlyIncomePotential: 800000,
    minimumTeamSize: 1,
    salesIntensity: 4,
    technicalIntensity: 3,
    aiLeverage: 5,
    inventoryRequired: false,
    faceOnCameraRequired: false,
    localServiceRequired: false,
    riskLevel: "medium",
    tags: ["AI", "自動化", "会社向け", "営業"],
    maxRisk: "最初のお客さんを見つけるために、ある程度の営業が必要。",
    first7Days: ["手伝う業種を1つ決める", "簡単な自動化デモを1本作る", "見込み客20社を探す"],
  },
  {
    id: "micro-saas",
    name: "会社向けの小さな月額Webサービス",
    summary: "1つの面倒な作業だけを楽にする小さなWebサービスを作り、毎月料金をもらう。",
    category: "月額Webサービス",
    marketOpportunityScore: 86,
    requiredBudget: 30000,
    requiredWeeklyHours: 15,
    monthsToFirstRevenue: 3,
    estimatedMonthlyIncomePotential: 1000000,
    minimumTeamSize: 1,
    salesIntensity: 3,
    technicalIntensity: 5,
    aiLeverage: 5,
    inventoryRequired: false,
    faceOnCameraRequired: false,
    localServiceRequired: false,
    riskLevel: "medium",
    tags: ["AI", "アプリ", "月額", "開発"],
    maxRisk: "作ることに時間を使いすぎて、本当に欲しい人がいるかの確認が遅れやすい。",
    first7Days: ["助けたい業種を1つ選ぶ", "10人に困りごとを聞く", "簡単な紹介ページと試作品を作る"],
  },
  {
    id: "short-video-agency",
    name: "ショート動画の制作・運用代行",
    summary: "お店や会社の短い動画を作り、投稿まで手伝って料金をもらう。",
    category: "動画代行",
    marketOpportunityScore: 76,
    requiredBudget: 5000,
    requiredWeeklyHours: 10,
    monthsToFirstRevenue: 1,
    estimatedMonthlyIncomePotential: 500000,
    minimumTeamSize: 1,
    salesIntensity: 3,
    technicalIntensity: 2,
    aiLeverage: 4,
    inventoryRequired: false,
    faceOnCameraRequired: false,
    localServiceRequired: false,
    riskLevel: "low",
    tags: ["動画", "SNS", "編集", "AI"],
    maxRisk: "安い仕事ばかり取ると、作業量のわりに利益が残りにくい。",
    first7Days: ["サンプル動画を3本作る", "料金を決める", "お店や会社に20件提案する"],
  },
  {
    id: "faceless-media",
    name: "顔出しなしのYouTube・ショート動画",
    summary: "AIで企画・台本・編集を効率化し、再生数や紹介料から収益を作る。",
    category: "動画メディア",
    marketOpportunityScore: 70,
    requiredBudget: 5000,
    requiredWeeklyHours: 10,
    monthsToFirstRevenue: 4,
    estimatedMonthlyIncomePotential: 400000,
    minimumTeamSize: 1,
    salesIntensity: 1,
    technicalIntensity: 2,
    aiLeverage: 5,
    inventoryRequired: false,
    faceOnCameraRequired: false,
    localServiceRequired: false,
    riskLevel: "medium",
    tags: ["動画", "YouTube", "SNS", "AI"],
    maxRisk: "再生数が安定せず、収益が出るまで時間がかかることがある。",
    first7Days: ["テーマを1つに絞る", "伸びている動画30本を見る", "最初の10本分の企画を作る"],
  },
  {
    id: "digital-products",
    name: "テンプレート・デジタル商品の販売",
    summary: "仕事で使うテンプレート、素材、AIプロンプト、教材などをネットで売る。",
    category: "デジタル商品",
    marketOpportunityScore: 68,
    requiredBudget: 3000,
    requiredWeeklyHours: 7,
    monthsToFirstRevenue: 2,
    estimatedMonthlyIncomePotential: 300000,
    minimumTeamSize: 1,
    salesIntensity: 2,
    technicalIntensity: 2,
    aiLeverage: 4,
    inventoryRequired: false,
    faceOnCameraRequired: false,
    localServiceRequired: false,
    riskLevel: "low",
    tags: ["AI", "教材", "テンプレート", "デジタル"],
    maxRisk: "似た商品が多いと値下げ競争になりやすい。",
    first7Days: ["誰の何の作業を楽にするか決める", "商品を1つ完成させる", "販売ページを公開する"],
  },
  {
    id: "niche-ecommerce",
    name: "小さなネットショップ・ドロップシッピング",
    summary: "特定ジャンルの商品に絞ってネットショップを作り、SNSや少額広告で売れるか試す。",
    category: "ネットショップ",
    marketOpportunityScore: 72,
    requiredBudget: 30000,
    requiredWeeklyHours: 12,
    monthsToFirstRevenue: 2,
    estimatedMonthlyIncomePotential: 600000,
    minimumTeamSize: 1,
    salesIntensity: 2,
    technicalIntensity: 2,
    aiLeverage: 3,
    inventoryRequired: false,
    faceOnCameraRequired: false,
    localServiceRequired: false,
    riskLevel: "high",
    tags: ["EC", "Shopify", "広告", "商品"],
    maxRisk: "広告費や返品で利益が減りやすい。最初は少額テストが必要。",
    first7Days: ["ジャンルを1つ選ぶ", "競合20店を見る", "商品候補を5個だけテストする"],
  },
  {
    id: "lead-generation",
    name: "地域のお店の集客代行",
    summary: "お店の紹介ページ、Googleマップ、広告などを手伝って問い合わせを増やす。",
    category: "地域サービス",
    marketOpportunityScore: 74,
    requiredBudget: 10000,
    requiredWeeklyHours: 10,
    monthsToFirstRevenue: 1,
    estimatedMonthlyIncomePotential: 600000,
    minimumTeamSize: 1,
    salesIntensity: 4,
    technicalIntensity: 2,
    aiLeverage: 3,
    inventoryRequired: false,
    faceOnCameraRequired: false,
    localServiceRequired: true,
    riskLevel: "low",
    tags: ["営業", "広告", "店舗", "地域"],
    maxRisk: "結果を数字で見せられないと継続契約につながりにくい。",
    first7Days: ["助ける業種を1つ決める", "無料チェック表を作る", "近くのお店20件に提案する"],
  },
  {
    id: "sales-agency",
    name: "営業・アポ取り代行",
    summary: "会社の代わりにメール・電話・SNSで見込み客へ連絡し、商談を作る。",
    category: "営業代行",
    marketOpportunityScore: 73,
    requiredBudget: 5000,
    requiredWeeklyHours: 12,
    monthsToFirstRevenue: 1,
    estimatedMonthlyIncomePotential: 800000,
    minimumTeamSize: 1,
    salesIntensity: 5,
    technicalIntensity: 1,
    aiLeverage: 3,
    inventoryRequired: false,
    faceOnCameraRequired: false,
    localServiceRequired: false,
    riskLevel: "low",
    tags: ["営業", "会社向け", "代行"],
    maxRisk: "営業が苦手な人には負担が大きい。",
    first7Days: ["得意そうな業種を決める", "提案文を3種類作る", "見込み客50件をリスト化する"],
  },
  {
    id: "app-freelance",
    name: "AIを使ったWeb・アプリ制作代行",
    summary: "AIコーディングを使って、小さなWebサイトや業務アプリを作って料金をもらう。",
    category: "制作代行",
    marketOpportunityScore: 78,
    requiredBudget: 10000,
    requiredWeeklyHours: 15,
    monthsToFirstRevenue: 2,
    estimatedMonthlyIncomePotential: 700000,
    minimumTeamSize: 1,
    salesIntensity: 3,
    technicalIntensity: 4,
    aiLeverage: 5,
    inventoryRequired: false,
    faceOnCameraRequired: false,
    localServiceRequired: false,
    riskLevel: "medium",
    tags: ["AI", "アプリ", "Web", "開発"],
    maxRisk: "依頼内容が途中で増えると、作業時間が想定より長くなりやすい。",
    first7Days: ["作るものを3種類に限定する", "見本を2本作る", "仕事サイトで10件応募する"],
  },
  {
    id: "newsletter-community",
    name: "専門情報の有料ニュースレター",
    summary: "特定テーマの役立つ情報を定期配信し、読者から毎月料金をもらう。",
    category: "情報配信",
    marketOpportunityScore: 65,
    requiredBudget: 1000,
    requiredWeeklyHours: 6,
    monthsToFirstRevenue: 3,
    estimatedMonthlyIncomePotential: 250000,
    minimumTeamSize: 1,
    salesIntensity: 2,
    technicalIntensity: 1,
    aiLeverage: 4,
    inventoryRequired: false,
    faceOnCameraRequired: false,
    localServiceRequired: false,
    riskLevel: "low",
    tags: ["情報", "月額", "AI", "コミュニティ"],
    maxRisk: "無料で読める情報との差を作る必要がある。",
    first7Days: ["読者を1タイプに絞る", "無料版を3本書く", "登録ページを作る"],
  },
];
