import type { BusinessCandidate, BusinessProfile } from "./types";

export const defaultBusinessProfile: BusinessProfile = {
  freeText: "少額で始められて、AIを使いながら一人で伸ばせるビジネスを探したい。",
  startingBudget: 100000,
  weeklyHours: 15,
  targetMonthlyIncome: 300000,
  timeToFirstRevenueMonths: 3,
  solo: true,
  salesComfort: 2,
  technicalComfort: 3,
  aiComfort: 4,
  inventoryOkay: false,
  faceOnCameraOkay: false,
  localServiceOkay: true,
  riskTolerance: "medium",
  interests: ["AI", "アプリ", "動画"],
  avoid: [],
};

export const businessCandidates: BusinessCandidate[] = [
  {
    id: "ai-automation-agency",
    name: "AI業務自動化代行",
    summary: "中小企業の定型業務をAI・ノーコードで自動化し、導入費と保守費を得る。",
    category: "AI・B2Bサービス",
    marketOpportunityScore: 82,
    requiredBudget: 30000,
    requiredWeeklyHours: 12,
    monthsToFirstRevenue: 1,
    estimatedMonthlyIncomePotential: 800000,
    minimumTeamSize: 1,
    salesIntensity: 4,
    technicalIntensity: 3,
    aiLeverage: 5,
    inventoryRequired: false,
    faceOnCameraRequired: false,
    localServiceRequired: false,
    riskLevel: "medium",
    tags: ["AI", "自動化", "B2B", "営業"],
    maxRisk: "案件獲得のための営業力と、顧客ごとの要件整理が必要。",
    first7Days: ["対象業種を1つ決める", "自動化デモを1本作る", "見込み客30社をリスト化する"],
  },
  {
    id: "micro-saas",
    name: "B2BマイクロSaaS",
    summary: "特定業務の小さな課題に絞ったWebサービスを月額課金で提供する。",
    category: "SaaS",
    marketOpportunityScore: 86,
    requiredBudget: 80000,
    requiredWeeklyHours: 18,
    monthsToFirstRevenue: 3,
    estimatedMonthlyIncomePotential: 1000000,
    minimumTeamSize: 1,
    salesIntensity: 3,
    technicalIntensity: 5,
    aiLeverage: 5,
    inventoryRequired: false,
    faceOnCameraRequired: false,
    localServiceRequired: false,
    riskLevel: "medium",
    tags: ["AI", "アプリ", "SaaS", "開発"],
    maxRisk: "作ることを優先しすぎると、需要検証前に時間を使い切りやすい。",
    first7Days: ["業種を1つ選ぶ", "10人に課題ヒアリングする", "LPと簡易デモを作る"],
  },
  {
    id: "short-video-agency",
    name: "ショート動画制作・運用代行",
    summary: "企業や店舗向けに短尺動画の企画・編集・投稿運用を提供する。",
    category: "コンテンツ代行",
    marketOpportunityScore: 76,
    requiredBudget: 20000,
    requiredWeeklyHours: 12,
    monthsToFirstRevenue: 1,
    estimatedMonthlyIncomePotential: 500000,
    minimumTeamSize: 1,
    salesIntensity: 3,
    technicalIntensity: 2,
    aiLeverage: 4,
    inventoryRequired: false,
    faceOnCameraRequired: false,
    localServiceRequired: false,
    riskLevel: "low",
    tags: ["動画", "SNS", "編集", "AI"],
    maxRisk: "単価が低い案件だけを取ると作業量に対して利益が残りにくい。",
    first7Days: ["業種別サンプルを3本作る", "料金プランを作る", "店舗・企業へ20件提案する"],
  },
  {
    id: "faceless-media",
    name: "顔出しなしYouTube・ショートメディア",
    summary: "AIを使って企画・台本・編集を効率化し、広告・アフィリエイト等で収益化する。",
    category: "メディア",
    marketOpportunityScore: 70,
    requiredBudget: 10000,
    requiredWeeklyHours: 10,
    monthsToFirstRevenue: 4,
    estimatedMonthlyIncomePotential: 400000,
    minimumTeamSize: 1,
    salesIntensity: 1,
    technicalIntensity: 2,
    aiLeverage: 5,
    inventoryRequired: false,
    faceOnCameraRequired: false,
    localServiceRequired: false,
    riskLevel: "medium",
    tags: ["動画", "YouTube", "SNS", "AI"],
    maxRisk: "再生数が安定せず、収益化まで無収入期間が続く可能性がある。",
    first7Days: ["テーマを1つに絞る", "競合30本を分析する", "最初の10本分の企画を作る"],
  },
  {
    id: "digital-products",
    name: "テンプレート・デジタル商品販売",
    summary: "業務テンプレート、素材、プロンプト、教材などを在庫なしで販売する。",
    category: "デジタル商品",
    marketOpportunityScore: 68,
    requiredBudget: 10000,
    requiredWeeklyHours: 8,
    monthsToFirstRevenue: 2,
    estimatedMonthlyIncomePotential: 300000,
    minimumTeamSize: 1,
    salesIntensity: 2,
    technicalIntensity: 2,
    aiLeverage: 4,
    inventoryRequired: false,
    faceOnCameraRequired: false,
    localServiceRequired: false,
    riskLevel: "low",
    tags: ["AI", "教材", "テンプレート", "デジタル"],
    maxRisk: "差別化が弱いと価格競争になり、集客に時間がかかる。",
    first7Days: ["顧客の作業を1つ選ぶ", "商品を1つ完成させる", "販売ページを公開する"],
  },
  {
    id: "niche-ecommerce",
    name: "ニッチEC・ドロップシッピング",
    summary: "特定ジャンルの商品に絞ってECストアを運営し、広告やSNSから集客する。",
    category: "EC",
    marketOpportunityScore: 72,
    requiredBudget: 120000,
    requiredWeeklyHours: 14,
    monthsToFirstRevenue: 2,
    estimatedMonthlyIncomePotential: 600000,
    minimumTeamSize: 1,
    salesIntensity: 2,
    technicalIntensity: 2,
    aiLeverage: 3,
    inventoryRequired: false,
    faceOnCameraRequired: false,
    localServiceRequired: false,
    riskLevel: "high",
    tags: ["EC", "Shopify", "広告", "商品"],
    maxRisk: "広告費・返品・仕入れ条件によって粗利が急に悪化しやすい。",
    first7Days: ["カテゴリを1つ選ぶ", "競合20店を比較する", "商品候補を10個テストする"],
  },
  {
    id: "lead-generation",
    name: "地域事業者向け集客・リード獲得代行",
    summary: "店舗や地域サービス向けにLP、MEO、広告、問い合わせ獲得をまとめて提供する。",
    category: "ローカルB2B",
    marketOpportunityScore: 74,
    requiredBudget: 30000,
    requiredWeeklyHours: 12,
    monthsToFirstRevenue: 1,
    estimatedMonthlyIncomePotential: 600000,
    minimumTeamSize: 1,
    salesIntensity: 4,
    technicalIntensity: 2,
    aiLeverage: 3,
    inventoryRequired: false,
    faceOnCameraRequired: false,
    localServiceRequired: true,
    riskLevel: "low",
    tags: ["営業", "広告", "店舗", "ローカル"],
    maxRisk: "成果を数字で示せないと継続契約につながりにくい。",
    first7Days: ["1業種に絞る", "無料診断シートを作る", "近隣30店舗に提案する"],
  },
  {
    id: "sales-agency",
    name: "営業代行・アポ獲得代行",
    summary: "B2B企業の新規開拓、メール・電話・SNSでの商談獲得を請け負う。",
    category: "営業サービス",
    marketOpportunityScore: 73,
    requiredBudget: 10000,
    requiredWeeklyHours: 15,
    monthsToFirstRevenue: 1,
    estimatedMonthlyIncomePotential: 800000,
    minimumTeamSize: 1,
    salesIntensity: 5,
    technicalIntensity: 1,
    aiLeverage: 3,
    inventoryRequired: false,
    faceOnCameraRequired: false,
    localServiceRequired: false,
    riskLevel: "low",
    tags: ["営業", "B2B", "代行"],
    maxRisk: "営業が苦手な人には継続負荷が高く、成果報酬だけだと収益が不安定。",
    first7Days: ["得意業種を決める", "提案文を3種類作る", "100件の見込み客リストを作る"],
  },
  {
    id: "app-freelance",
    name: "AI活用Web・アプリ受託開発",
    summary: "AIコーディングを活用して小規模Webサイトや業務アプリを受託する。",
    category: "受託開発",
    marketOpportunityScore: 78,
    requiredBudget: 30000,
    requiredWeeklyHours: 18,
    monthsToFirstRevenue: 2,
    estimatedMonthlyIncomePotential: 700000,
    minimumTeamSize: 1,
    salesIntensity: 3,
    technicalIntensity: 4,
    aiLeverage: 5,
    inventoryRequired: false,
    faceOnCameraRequired: false,
    localServiceRequired: false,
    riskLevel: "medium",
    tags: ["AI", "アプリ", "Web", "開発"],
    maxRisk: "見積もりミスや仕様追加で工数が膨らみやすい。",
    first7Days: ["作れるものを3つに限定する", "デモを2本作る", "クラウドソーシングで10件応募する"],
  },
  {
    id: "newsletter-community",
    name: "専門ニュースレター・有料コミュニティ",
    summary: "特定テーマの情報整理や独自分析を定期配信し、月額課金につなげる。",
    category: "コンテンツサブスク",
    marketOpportunityScore: 65,
    requiredBudget: 5000,
    requiredWeeklyHours: 7,
    monthsToFirstRevenue: 3,
    estimatedMonthlyIncomePotential: 250000,
    minimumTeamSize: 1,
    salesIntensity: 2,
    technicalIntensity: 1,
    aiLeverage: 4,
    inventoryRequired: false,
    faceOnCameraRequired: false,
    localServiceRequired: false,
    riskLevel: "low",
    tags: ["情報", "サブスク", "AI", "コミュニティ"],
    maxRisk: "無料情報との差別化と、継続して読む理由を作る必要がある。",
    first7Days: ["読者像を1人に絞る", "無料版を3本書く", "登録ページを作る"],
  },
];
